{% set name = "pism" %}
{% set version = "2.1" %}
{% set build = 0 %}

#{% set mpi = mpi or 'mpich' %}
{% set mpi = "openmpi" %}

package:
  name: {{ name }} 
  version: {{ version }}

source:
  url: https://github.com/pism/pism/archive/v{{ version }}.tar.gz
  sha256: 9d7e9854b58180df58d38fdd3eaa993a1e247548dfe183a8753a3f15190b6aaa

build:
  skip: true  # [win]
  number: {{ build }}

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - make
    - swig
    - nose
    - gnuconfig   # [unix]
    - {{ mpi }}  # [mpi == 'openmpi' and build_platform != target_platform]
  host:
    - python
    - pip
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw
    - fftw * mpi_{{ mpi }}_*
    - netcdf-cxx4
    - cmake
    - gsl
    - {{ mpi }}
    - udunits2
    - proj
    - lapack
    - petsc
    - petsc4py
    - nose
    - doxygen
    - tbb=2020.2
  run:
    - python
    - pip
    - hdf5
    - hdf5 * mpi_{{ mpi }}_*
    - fftw
    - fftw * mpi_{{ mpi }}_*
    - netcdf-cxx4
    - cmake
    - gsl
    - {{ mpi }}
    - udunits2
    - proj
    - lapack
    - petsc
    - petsc4py
    - nose
    - doxygen
    - tbb=2020.2
    - xarray
    - pandas
    - matplotlib

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - simplejson
    - simplejson.tests
  # For python packages, it is useful to run pip check. However, sometimes the
  # metadata used by pip is out of date. Thus this section is optional if it is
  # failing.
  requires:
    - pip
  commands:
    - pip check
    - pismr

about:
  home: https://github.com/pism/pism
  summary: 'PISM, a Parallel Ice Sheet Model'
  description: |
    The Parallel Ice Sheet Model is an open source, parallel, high-resolution ice sheet model:
      - hierarchy of available stress balances
      - marine ice sheet physics, dynamic calving fronts
      - polythermal, enthalpy-based conservation of energy scheme
      - extensible coupling to atmospheric and ocean models
      - verification and validation tools
      - `documentation <pism-manual_>`_ for users and developers
      - uses MPI_ and PETSc_ for parallel simulations
      - reads and writes `CF-compliant <cf_>`_  NetCDF_ files
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://pism.io
  dev_url: https://github.com/pism/pism

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - aaschwanden
    - ckhroulev
