{% set name = "pism-dev" %}
{% set version = "2.3.99" %}
{% set build = 0 %}


package:
  name: {{ name }}
  version: {{ version }}
source:
  git_url: https://github.com/pism/pism.git
  git_branch: feature/pyproject
build:
  skip: true  # [win or mpi == 'mpich']
  number: {{ build }}

  # add build string so packages can depend on mpi variants explicitly:
  # `pism * mpi_mpich_*` for mpich
  # `pism * mpi_openmpi_*` for openmpi
  # `pism * mpi_*` for any mpi

  {% set mpi = mpi or "mpich" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
    - {{ name }} * {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake >=3.20
    - pkg-config
    - make
    - swig
    - gnuconfig   # [unix]
  host:
    - python
    - pip
    - scikit-build-core >=0.10
    - fftw
    - libnetcdf * mpi_{{ mpi }}_*
    - gsl >=1.15
    - {{ mpi }} >=5  # [mpi == "openmpi"]
    - {{ mpi }}      # [mpi != "openmpi"]
    - udunits2
    - proj
    - libsqlite  # Needed for pkg-config to validate proj.pc Requires.private
    - libtiff    # Needed for pkg-config to validate proj.pc Requires.private
    - libcurl    # Needed for pkg-config to validate proj.pc Requires.private
    - zlib       # Needed for pkg-config to validate libcurl.pc Requires.private
    - liblzma-devel  # Needed for `pkg-config --exists proj`
    - petsc
    - petsc4py
    - yac * mpi_{{ mpi }}_*
    - libopenblas
    - yaxt * mpi_{{ mpi }}_*
  run:
    - python
    - fftw
    - libnetcdf * mpi_{{ mpi }}_*
    - gsl >=1.15
    - {{ mpi }}
    - udunits2
    - proj
    - petsc
    - petsc4py
    - yac * mpi_{{ mpi }}_*
    - libopenblas
    - yaxt * mpi_{{ mpi }}_*
    - netcdf4 # needed for asynchronous writing
    - xarray

test:
  imports:
    - PISM
  requires:
    - pip
  commands:
    - pip check
    - "mpirun -np 1 pism -eisII A -Mx 5 -My 5 -y 1e3 -spatial_times 100 -spatial_file spatial_eismint-A.nc -spatial_vars thk -o eismint-A.nc : -n 1 pism_async_writer"
    
about:
  home: https://github.com/pism/pism
  summary: PISM, a Parallel Ice Sheet Model
  description: |
    The Parallel Ice Sheet Model is an open source, parallel, high-resolution ice sheet model:
      - hierarchy of available stress balances
      - marine ice sheet physics, dynamic calving fronts
      - polythermal, enthalpy-based conservation of energy scheme
      - extensible coupling to atmospheric and ocean models
      - verification and validation tools
      - `documentation <pism-manual_>`_ for users and developers
      - uses MPI_ and PETSc_ for parallel simulations
      - reads and writes `CF-compliant <cf_>`_  NetCDF_ files
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  doc_url: https://pism.io
  dev_url: https://github.com/pism/pism

extra:
  recipe-maintainers:
    - aaschwanden
    - ckhroulev
    - jhkennedy
